
name: radiomanager-cli
version: '0.0.1' 
summary: Bash RadioManager client
description: |
  Command line interface to the RadioManager API v2

grade: stable
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
    radiomanager-cli:
        command: radiomanager-cli
    bash:
        command: bash

parts:
        gnu-bash:
            source: http://ftp.gnu.org/gnu/bash/bash-4.3.tar.gz
            plugin: autotools
            configflags: ["--infodir=/var/bash/info"]

