--- 
apps: 
  radiomanager-cli: 
    command: radiomanager-cli
    plugs: 
      - network
confinement: strict
description: |
    Command line interface written in bash to the Pluxbox RadioManager API v2
    See http://pluxbox.com for more information.
grade: stable
name: radiomanager-cli
parts: 
  radiomanager-cli: 
    plugin: dump
    source: "https://github.com/Pluxbox/radiomanager-cli.git"
    stage-packages: 
      - curl
      - bsdmainutils
summary: "Command line interface to Pluxbox RadioManager client"
version: "1.0.84"
