name: radiomanager-cli
version: '1.0.83' 
summary: Command line interface to Pluxbox RadioManager client
description: |
  Command line interface written in bash to the Pluxbox RadioManager API v2
  See http://pluxbox.com for more information.

grade: stable
confinement: strict

apps:
    radiomanager-cli:
        command: radiomanager-cli

parts:
    radiomanager-cli:
        source: https://github.com/Pluxbox/radiomanager-cli.git
        plugin: dump
        stage-packages:
            - curl
